/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teng_carn_MainActivity_AutoFocusCallback */

#ifndef _Included_com_teng_carn_MainActivity_AutoFocusCallback
#define _Included_com_teng_carn_MainActivity_AutoFocusCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
