/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_teng_carn_MainActivity_priviewCallBack */

#ifndef _Included_com_teng_carn_MainActivity_priviewCallBack
#define _Included_com_teng_carn_MainActivity_priviewCallBack
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
